### ISSUE TITLE
[Feature request] Use note data (description, title) for Opengraph Tags

### ISSUE THREAD

**Issue by SemyonSinchenko** [Artawower/orgnote#3]
**Is your feature request related to a problem? Please describe.**
Currently sharing of the published note show generic information about org-note instead of the title and description of the note itself.

**Describe the solution you'd like**
Title and description (`#+TITLE:`, `#+DESCRIPTION:`) are shown in preview of the shared note.

**Describe alternatives you've considered**
.

**Additional context**
[An example of og tags that are currently provided](https://www.opengraph.xyz/url/https%3A%2F%2Forg-note.com%2Fdetail%2Fc904151a-dd38-4d37-aaac-992af3c8d77c)

```html
<!-- HTML Meta Tags -->
<title>OrgNote</title>
<meta name="description" content="OrgNote app. OrgNote is a note-taking app for organizing your thoughts and ideas. It is based on the emacs org-roam package and org-mode format.">
```

Could be cool to have at least title -> name and description -> content.

**Comment by Artawower** [comment]
Thanks for the proposal! Note publishing and SEO optimization is one of the crucial to this project.

I [played a bit with dynamic meta tags](https://github.com/Artawower/orgnote-client/tree/feat/server-side-rendering) (not released yet), but the problem is that these keywords applied in runtime only on the client side. When some resources check it by http request to the server the get just html template without runtime evaluation. In this case this approach will not work and I need to implement server-side rendering. 
It was not supposed to be a difficult task, cause i don't need to have a state or authentication on the server side for public notes, but when i played with Quasar SSR i faced with 2 different problems:

- [third party esm modules](https://github.com/quasarframework/quasar/issues/15162)
- [meta.import for workers](https://discord.com/channels/415874313728688138/856517489542561792/1231300475622654003)

I have a potential idea how to fix the second one, but i need to deep into the first problem.


Initially i thought about creating an external service that allows to publish notes in a blog-like style. 
There are a few advantages of using this approach:
- SEO optimization (og tags)
- More quick render (if use framework like astro or smth like that)

Potentially it could solve the problem with og tags and other SEO stuff, but i have a concern about it, cause it's easier to support only one app with a unified interface

I'll speculate which solution is easier to maintain

**Comment by Artawower** [comment]
The last release was supposed to implement this feature (the change is only applied to the web and therefore there is no need to update mobile apps).

However, the first point of the problem with the current revision could not be solved and I had to switch to the beta version `@quasar/app-vite 2.0`, which may cause some additional problems. From the good news, this only affects the web version.

I added support for the following tags: https://github.com/artawower/orgnote-client/blob/master/src/hooks/current-note-meta.ts#L104.

And now it looks as follows
https://www.opengraph.xyz/url/https%3A%2F%2Forg-note.com%2Fdetail%2F0b5155df-57f9-495c-9d04-a2ce9bb1d0cb

If there are any other requests or problems with the current solution, let me know.
