### ISSUE TITLE
[Bug] For some reason title is rendered as a keyword not as title

### ISSUE THREAD

**Issue by SemyonSinchenko** [Artawower/orgnote#4]
### Thank you for the bug report

- [X] I am using the latest version of the `OrgNote` app.
- [X] I already checked other related issues
- [X] I have read the [WIKI](https://github.com/Artawower/orgnote/wiki)

### Bug description and steps to reproduce

On [that](https://org-note.com/detail/5bb3c30a-e489-45b2-bc3f-141c55109052) page title is rendered like it is a keyword:
![image](https://github.com/Artawower/orgnote/assets/29755009/44db23d0-a62a-497d-aaab-74507edfc3e2)

Overall syntax looks good from the org point of view... I checked on both desktop and mobile and result is the same.

At the same moment, all the tags and meta information are parsed correctly: the page is visible on the graph and in a dashboard.

### Debug info

I'm using it not from emacs but from web.

**Comment by Artawower** [comment]
Thanks for the bug report and clear example! Actually the cause was in the codemirror widget range (a nested list inside the quote block). There was incorrect sorting in it.

[Will be fixed in the next release.](https://github.com/Artawower/orgnote-client/pull/25)

> Debug info
I'm using it not from emacs but from web.

By the way, I think the instructions in the GitHub issue template may need clarification. Although they don't directly apply to this specific issue due to the clear public example, I wanted to mention that we also have M-x functionality and additional debugging information available here. This might be useful if you encounter a UI-specific issue in the future.

![2024-04-24_23-18](https://github.com/Artawower/orgnote/assets/16963833/9e50f8af-212a-46e6-9176-3cc42bf4a420)
![image](https://github.com/Artawower/orgnote/assets/16963833/15211433-978f-4d2e-b911-5cda1f348422)

There are also public logs ("show logs") in this menu which can be useful for debugging on android devices

**Comment by SemyonSinchenko** [comment]
It looks like it was resolved by the latest release. Thank you a lot!
